#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorReflection)
#pragma config(Sensor, in2,    midLight,       sensorReflection)
#pragma config(Sensor, in3,    rightLight,     sensorReflection)
#pragma config(Sensor, in4,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEn,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_8,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           rightSlide,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSlide,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
#pragma config(Motor,  port8,           leftIntake,    tmotorVex393_MC29, openLoop, encoderPort, I2C_8)
#pragma config(Motor,  port9,           rightIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          elevator,      tmotorVex393_HBridge, openLoop, encoderPort, I2C_7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define MM_PER_REV 295.16
#define ROBOT_WIDTH_MM 310.0
#define ROBOT_LENGTH_MM 530.0
#define ROBOT_WHEEL_DIAMETER_MM 94.0
#define ROBOT_DEG_PER_ROTATION 57.6

bool printAngle = false;
bool printEncodersMM = false;
bool printEncodersRot = false;


// SOME UTIL METHODS
bool isInRangeOf(double input, double goal, double threshold) {
	if ( input < goal + threshold && input > goal - threshold) {
		return true;
	}
	return false;
}

#include "Drive.c"
task main()
{
	startTask(driveTracker);
	startTask(driveNavigator);
	/*setDrive(127);
	wait1Msec(2000);
	setDrive(0);
	wait1Msec(2000);
	resetEncoders();*/
	while(driveAngle > -45) {
		setLeftSide(30);
		setRightSide(-30);
	}
	setDrive(0);
	wait1Msec(250);
	moveForwardMM(390);

	while(true)
	{
		wait1Msec(250);
	}
}
