#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorReflection)
#pragma config(Sensor, in2,    midLight,       sensorReflection)
#pragma config(Sensor, in3,    rightLight,     sensorReflection)
#pragma config(Sensor, in4,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEn,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_8,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightFront,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           leftFront,     tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           rightSlide,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSlide,     tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_6)
#pragma config(Motor,  port8,           leftIntake,    tmotorVex393_MC29, openLoop, encoderPort, I2C_8)
#pragma config(Motor,  port9,           rightIntake,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          elevator,      tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MM_PER_REV 295.16
#define ROBOT_WIDTH_MM 310.0
#define ROBOT_LENGTH_MM 530.0
#define ROBOT_WHEEL_DIAMETER_MM 94.0
#define ROBOT_DEG_PER_ROTATION 57.6

bool printAngle = false;
bool printEncodersMM = false;
bool printEncodersRot = false;


// SOME UTIL METHODS
bool isInRangeOf(double input, double goal, double threshold) {
	if ( input < goal + threshold && input > goal - threshold) {
		return true;
	}
	return false;
}

#include "Drive.c"
#include "Arm.c"
#include "Shooter.c"
task main()
{
	startTask(driveTracker);
	startTask(driveNavigator);
	startTask(armNavigator);

	setShooter(127);
	motor[elevator] = 127;
	wait1Msec(500);
	addToAngle(-26);
	waitForDrive();
	setShooter(-127);
	motor[elevator] = -127;
	moveForwardMM(1200);
	waitForDrive();
	setShooter(0);
	motor[elevator] = 0;
	moveArmTo(350);
	addToAngle(-112);
	waitForDrive();
	moveForwardMM(1200);
	waitForDrive();
	shoot(105);
	moveArmTo(0);
	moveForwardMM(100);
	waitForDrive();

	// get stack 2
	motor[elevator] = -127;
	setShooter(-127);
	addToAngle(-154);
	waitForDrive();
	moveForwardMM(500);
	waitForDrive();
	moveArmTo(600);
	motor[elevator] = 0;
	setShooter(0);
	moveForwardMM(-500);
	waitForDrive();

	addToAngle(-46);
	waitForDrive();
	shoot(90); // shoot stack 2

	moveArmTo(0);
	addToAngle(80);
	waitForDrive();
	setShooter(-127);
	motor[elevator] = -127;
	moveForwardMM(410);
	waitForDrive();
	wait1Msec(500);
	moveArmTo(350);
	addToAngle(120);
	waitForDrive();
	shoot(90);

	// go to get stack 4
	moveArmTo(0);
	addToAngle(85);
	waitForDrive();
	intake();
	moveForwardMM(800);
	waitForDrive();
	neutral();
	moveArmTo(600);
	addToAngle(80);
	waitForDrive();
	moveForwardMM(-1000);
	waitForDrive();
	shoot(90);

	// go to get stack 5
	moveArmTo(0);
	moveForwardMM(350);
	waitForDrive();
	addToAngle(-83);
	waitForDrive();
	intake();
	moveForwardMM(940);
	waitForDrive();
	neutral();
	moveArmTo(350);
	moveForwardMM(300);
	waitForDrive();
	shoot(90);

	// go to get stack 6
	moveArmTo(0);
	moveForwardMM(-300);
	waitForDrive();
	intake();
	addToAngle(-85);
	waitForDrive(2500);
	moveForwardMM(100);
	waitForDrive();
	wait1Msec(500);
	moveForwardMM(-100);
	waitForDrive();
	addToAngle(-100);
	waitForDrive();
	moveForwardMM(200);
	waitForDrive();
	neutral();
	moveArmTo(600);
	moveForwardMM(-1800);
	waitForDrive();
	shoot(90);

	// next stack
	moveArmTo(0);
	intake();
	waitForArm(5000);
	moveForwardMM(880);
	waitForDrive();
	addToAngle(-20);
	waitForDrive();
	moveArmTo(600);
	neutral();
	moveForwardMM(-1000);
	waitForDrive();
	shoot(90);

	// next stack
	moveArmTo(0);
	moveForwardMM(400);
	waitForDrive();
	intake();
	addToAngle(-90);
	waitForDrive();
	moveForwardMM(900);
	waitForDrive();
	neutral();
	moveArmTo(600);
	addToAngle(45);
	waitForDrive();
	moveForwardMM(-300);
	waitForDrive();
	shoot(100);

	// last stack
	moveArmTo(0);
	intake();
	wait1Msec(750);
	addToAngle(-85);
	waitForDrive(2000);
	wait1Msec(500);
	moveForwardMM(400);
	waitForDrive();
	neutral();
	moveForwardMM(-400);
	waitForDrive();
	moveArmTo(350);
	addToAngle(-140);
	waitForDrive();
	setShooter(127);
	motor[elevator] = 127;
	while(true)
	{
		wait1Msec(250);
	}
}
